### ISSUE TITLE
Port to 2019.2

### ISSUE THREAD

**Issue by pegaillardon** [Digilent/Genesys-ZU-OOB-os#1]
Hi,
Are there plans to port the example project to Petalinux 2019.2? I have been poking around and end up with patching problems on the fsbl.
Thanks.
PE

**Comment by elodg** [comment]
Official port will be 2020.1. However, your fsbl patching issues might be solved by https://github.com/Digilent/embeddedsw/tree/genesys-zu_19.2.

**Comment by pegaillardon** [comment]
Thanks a lot, Elod.

Before migrating to 2019.2, I am trying the repo on 2019.1. While I can build just fine, I end up with only an Image file in the prebuilt folder instead of an image.ub file (that is present in the images/linux folder). Do you have any ideas what is going wrong?
I just clone the repo, sources the petalinux 2019.1 settings and ran the petalinux-build and petalinux-package commands.

Nevertheless, I tried booting with the image.ub file (available again in the images/linux folder) and it boots fine, but get stuck right in the middle of boot up after the following message: "ff010000.serial: ttyPS1 at MMIO 0xff010000 (irq = 47, base_baud = 6250000) is a xuartps
That doesn't look very normal. Any inputs about that?

Thanks,
PE

**Comment by elodg** [comment]
I am not sure what your boot method or work flow is. We mostly use SD boot and the following tools:
- petalinux-build will output to images/linux, including image.ub
- petalinux-package --boot will create BOOT.BIN.
Just take BOOT.BIN and image.ub from images/linux. Once you do that, let me know if you still get the boot error. I trust you are getting the error with your custom image and not with the out-of-box image the SD card shipped with.

No idea why --prebuilt does not copy image.ub.

**Comment by elodg** [comment]
Will not fix. Next supported version is expected to be 2020.1.
